### ISSUE TITLE
关于编译了x86_64的 openwrt_nezha使用问题

### ISSUE THREAD

**Issue by jidanyunmian** [Erope/openwrt_nezha#1]
已经编译好luci-app-nezha，并使用生效，探针也显示，但是接口是监控lan的，我想让他监控wan接口，需要怎么做呢？另外如何禁止更新？若是使用一键脚本，可以编辑 /etc/systemd/system/nezha-agent.service，在 ExecStart= 这一行的末尾加上，但openwrt_nezha要怎么额外添加参数使其生效呢？

**Comment by jidanyunmian** [comment]
![20220504035052](https://user-images.githubusercontent.com/29531196/166555122-42399301-632b-4fc3-9d57-28a1340511bb.png)

**Comment by Erope** [comment]
1. 对于Agent来说无法手动指定网卡，没法实现
2. 编译前可以在/luci-app-nezha/root/etc/init.d/nezha-agent，即https://github.com/Erope/openwrt_nezha/blob/main/luci-app-nezha/root/etc/init.d/nezha-agent 在第14行后面修改，或者编译后去/etc/init.d/nezha-agent中修改

**Comment by jidanyunmian** [comment]
![CAGLX)5RTJT0TIF%PK(WAHH](https://user-images.githubusercontent.com/29531196/166653291-e212f83c-71f5-4958-8951-d9eb87cea337.png)
是这个吗

**Comment by Erope** [comment]
> ![CAGLX)5RTJT0TIF%PK(WAHH](https://user-images.githubusercontent.com/29531196/166653291-e212f83c-71f5-4958-8951-d9eb87cea337.png) 是这个吗

是的

**Comment by jidanyunmian** [comment]
> > ![CAGLX)5RTJT0TIF%PK(WAHH](https://user-images.githubusercontent.com/29531196/166653291-e212f83c-71f5-4958-8951-d9eb87cea337.png) 是这个吗
> 
> 是的

居然是怎么改呢 看不太懂

**Comment by Erope** [comment]
> 第14行，-s -p -d 后面加上自己想要的参数

**Comment by Erope** [comment]
> > > ![CAGLX)5RTJT0TIF%PK(WAHH](https://user-images.githubusercontent.com/29531196/166653291-e212f83c-71f5-4958-8951-d9eb87cea337.png) 是这个吗
> > 
> > 
> > 是的
> 
> 居然是怎么改呢 看不太懂

第14行，-s -p -d 后面加上自己想要的参数

**Comment by jidanyunmian** [comment]
> 1. 无法手动指定网卡

无法手动指定网卡么 行吧 我先把自动更新Agent关掉了
