### ISSUE TITLE
安装后openwrt管理页面找不到nezha

### ISSUE THREAD

**Issue by lllAlex2333** [Erope/openwrt_nezha#3]
装了release里的luci和x86_64安装包，但是在luci管理页面找不到nezha相关的东西？
还是说nezha只后台运行，没有对应luci？

**Comment by Erope** [comment]
> 装了release里的luci和x86_64安装包，但是在luci管理页面找不到nezha相关的东西？ 还是说nezha只后台运行，没有对应luci？

目前只支持低版本op，高版本op可安装但不会有显示
