### ISSUE TITLE
Nezha-Agent进程阻塞关机

### ISSUE THREAD

**Issue by qianchen36** [Erope/openwrt_nezha#5]
平台是r4s，安装了nezha-agent的ipk包后reboot和poweroff指令被阻塞，必须手动kill掉agent进程后才能正常重启或关机

**Comment by Erope** [comment]
可能是init.d中没有stop方法导致的，但我现在没有机器可以测试，非常抱歉；
之前我在x86上运行是没有这个问题的。

**Comment by qianchen36** [comment]
> 可能是init.d中没有stop方法导致的，但我现在没有机器可以测试，非常抱歉；
> 之前我在x86上运行是没有这个问题的。

init.d里是有stop方法的
不过我的sd卡根分区因为意外断电现在变成只读分区了，不知道会不会和这个有关
最近没空折腾，只能将就用了

**Comment by Erope** [comment]
> > 可能是init.d中没有stop方法导致的，但我现在没有机器可以测试，非常抱歉；
> > 之前我在x86上运行是没有这个问题的。
> 
> init.d里是有stop方法的 不过我的sd卡根分区因为意外断电现在变成只读分区了，不知道会不会和这个有关 最近没空折腾，只能将就用了

有可能，先凑合用吧...
